#!/usr/bin/env python3
"""Regenerate the NVIDIA routes' lock files (scripts/locks/*.txt) with uv.

    python scripts/lock_nvidia_routes.py            # every route
    python scripts/lock_nvidia_routes.py trellis    # one

Unpinned installs broke three times in one day as upstreams moved (torch outran
flash-attn's wheels, bpy 4.0 left PyPI, setuptools dropped pkg_resources). Each route's
bootstrap now installs everything but PyTorch from a lock resolved here, for Linux x86_64
and Python 3.11, against the PyTorch version that route is tested with.

PyTorch itself stays out of the locks: the bootstrap picks its build per card (CUDA 12 vs
13, Blackwell), and that choice is tested separately. basicsr's setup.py imports torch,
so the bootstrap installs PyTorch first and the lock with --no-build-isolation.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
import tempfile
import urllib.request
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "scripts"))

import bootstrap_hunyuan_cuda as hunyuan  # noqa: E402
import bootstrap_sf3d as sf3d  # noqa: E402
import bootstrap_trellis_cuda as trellis  # noqa: E402

ROUTES = ("trellis", "hunyuan", "sf3d")

LOCKS = REPO / "scripts" / "locks"
TORCH_INDEX = "https://download.pytorch.org/whl/"
# Left out of every lock: the bootstrap installs PyTorch for the card it finds.
TORCH_FAMILY = re.compile(r"^(torch|torchvision|torchaudio|triton|nvidia-[\w-]+|cuda-[\w-]+)==", re.I)


def keep_line(line: str) -> bool:
    """Drop PyTorch and its CUDA wheels from a compiled lock; keep everything else."""
    return not TORCH_FAMILY.match(line.strip())


def hunyuan_inputs(upstream: str) -> list[str]:
    return [*hunyuan.filter_requirements(upstream), hunyuan.SETUPTOOLS_PIN]


def sf3d_inputs(upstream: str) -> list[str]:
    """SF3D's own list minus its two local extensions, which the bootstrap builds."""
    return [line.strip() for line in upstream.splitlines()
            if line.strip() and not line.startswith("#") and not line.startswith("./")]


def viewer_torch_pins(lock: Path = REPO / "requirements.lock") -> list[str]:
    """SF3D installs into the viewer's own environment, so it resolves against the
    PyTorch the viewer's lock already installed (PyPI's, CUDA-enabled on Linux)."""
    pins = [line.split(";")[0].strip() for line in lock.read_text().splitlines()
            if line.startswith(("torch==", "torchvision=="))]
    return sorted(pins)


def compile_lock(inputs: list[str], torch_pins: list[str], tag: str | None,
                 out: Path) -> None:
    with tempfile.TemporaryDirectory() as scratch:
        req = Path(scratch) / "in.txt"
        req.write_text("\n".join([*inputs, *torch_pins]) + "\n")
        raw = Path(scratch) / "out.txt"
        subprocess.run(["uv", "pip", "compile", "--quiet", "--python-version", "3.11",
                        "--python-platform", "x86_64-manylinux_2_28",
                        *(["--extra-index-url", TORCH_INDEX + tag,
                           "--index-strategy", "unsafe-best-match"] if tag else []),
                        "--no-header", "--no-annotate", str(req), "-o", str(raw)], check=True)
        kept = [line for line in raw.read_text().splitlines() if line and keep_line(line)]
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(f"# Generated by scripts/lock_nvidia_routes.py for {torch_pins[0]}\n"
                   f"# ({tag or 'PyPI'}); PyTorch itself is installed separately.\n"
                   + "\n".join(kept) + "\n")
    print(f"wrote {out.relative_to(REPO)} ({len(kept)} packages)")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("routes", nargs="*", help=f"{', '.join(ROUTES)} (default: all)")
    args = parser.parse_args(argv)
    args.routes = args.routes or list(ROUTES)
    unknown = set(args.routes) - set(ROUTES)
    if unknown:
        parser.error(f"unknown route: {', '.join(sorted(unknown))}")
    if "trellis" in args.routes:
        compile_lock(trellis.BASIC,
                     [f"torch=={trellis.TORCH_FOR_FLASH_WHEEL}",
                      f"torchvision=={trellis.TORCHVISION_FOR_FLASH_WHEEL}"],
                     "cu128", trellis.PACKAGE_LOCK)
    if "hunyuan" in args.routes:
        url = (f"https://raw.githubusercontent.com/Tencent-Hunyuan/Hunyuan3D-2.1/"
               f"{hunyuan.COMMIT}/requirements.txt")
        with urllib.request.urlopen(url) as response:
            upstream = response.read().decode()
        torch_version, vision_version, tag, _ = hunyuan.TORCH["tested"]
        compile_lock(hunyuan_inputs(upstream),
                     [f"torch=={torch_version}", f"torchvision=={vision_version}"],
                     tag, hunyuan.PACKAGE_LOCK)
    if "sf3d" in args.routes:
        url = (f"https://raw.githubusercontent.com/Stability-AI/stable-fast-3d/"
               f"{sf3d.COMMIT}/requirements.txt")
        with urllib.request.urlopen(url) as response:
            upstream = response.read().decode()
        compile_lock(sf3d_inputs(upstream), viewer_torch_pins(), None, sf3d.PACKAGE_LOCK)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
